### ISSUE TITLE
dev-deploy return error `Account undefined is not found in testnet`

### ISSUE THREAD

**Issue by lqueiroga** [near/near-cli#1086]
**Describe the bug**
When running `near dev-deploy --wasmFile` I get the message `Account undefined is not found in testnet`

Dev account is not in testnet and when trying to delete near dev account I get this error:
`Error: Can not sign transactions for account dev-1707339621480-58407081000882 on network testnet, no matching key pair found in InMemorySigner(MergeKeyStore(UnencryptedFileSystemKeyStore(/home/developer/.near-credentials), UnencryptedFileSystemKeyStore(/home/developer/WKS/platform/near/startup-registry-contract/neardev))).`

**To Reproduce**
1. run command `near dev-deploy --wasmFile <wasm_file>` 
2. See error

**Terminal**
```
> near dev-deploy --wasmFile ./target/wasm32-unknown-unknown/release/mytest.wasm

Account undefined is not found in testnet
```

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.6
 - near-cli version: 3.5.0

**Comment by gagdiez** [comment]
the error was happening because it is no longer possible to create `top level accounts (TLA)`. `dev-deploy` was creating accounts in the form `dev-X-Y`, which were `TLA`. Now, only sub-accounts of a domain can be created (e.g. `.testnet`, `.mainnet`, `.sweat`).

I have released a new version of `near-cli` which allows to easily imitate the work of `dev-deploy`, you just need to run:
- `near create-account <accountId> --useFaucet`
- `near deploy <accountId> <wasmFile>`

**Comment by lqueiroga** [comment]
Nice thanks for the update

**Comment by edwardchew97** [comment]
@gagdiez 
I was using this command near create-account <accountId> --useFaucet and receive an error of
`The faucet reported no errors, but we cannot find 5z5b526ihj.rektdegen.testnet. Check if it exists with "near state 5z5b526ihj.rektdegen.testnet --networkId testnet".`

By any chance you have an insight on this? Thanks
