### ISSUE TITLE
Stop abusing NODE_ENV

### ISSUE THREAD

**Issue by frol** [near/near-cli#239]
`NODE_ENV` is a special environment variable used by Node.js, we should use our own name to avoid the collision.

Also, it would be great to have a regular CLI argument for this feature.

**Comment by vgrichina** [comment]
I think we are using it as intended. People use the same shit to manage say different DB environments in Node, don't see how we are different.

I agree that having a separate CLI argument that explicitly selects NEAR environment might be useful though.

**Comment by janedegtiareva** [comment]
+1 to adding CLI argument.

**Comment by ilblackdragon** [comment]
Why not just NEAR_ENV? 
It's totally possible that people want to have few different NEAR envs and for example have production or development for NODE independently.

**Comment by ilblackdragon** [comment]
Can we prioritize this?...
Especially using `production` ... I went to codebase to figure out why mainnet doesn't work :(

**Comment by chadoh** [comment]
For local dev, I haven't yet wanted to override both RPC and Wallet at the same time, and I think it's strange that our currently-suggested `config.js` assumes that I would.

Also, I find it annoying that we export a `getConfig` function when we could just export the constants themselves. This whole `config.js` seems like a way to export some environment variables to me. See suggested simplification here: https://github.com/near-examples/guest-book/pull/78

I've been wondering if we can move this whole config to a file like `.nearconfig`, and possibly put credentials in this file as well, as suggested here: https://github.com/near/near-shell/pull/339#pullrequestreview-402944666

Such a file could live in a user's home directory and then have specific settings overridden per-directory.

Thoughts?

**Comment by vgrichina** [comment]
> For local dev, I haven't yet wanted to override both RPC and Wallet at the same time, and I think it's strange that our currently-suggested config.js assumes that I would.

Not sure what do you mean. If you are overriding RPC you generally need to override the wallet, otherwise you have a wallet which doesn't work with your RPC.

> Also, I find it annoying that we export a getConfig function when we could just export the constants themselves. This whole config.js seems like a way to export some environment variables to me. See suggested simplification here: near-examples/guest-book#78

We have far more pressing devx issues to solve:
   - support of multiple contracts
   - data migration when upgrading contact
   - batch import/export of contract data
   - error handling being a mess
   - no demo taking advantage of multiple shards
   - etc
I suggest we focus on big picture vs trying to do marginal improvements to config file (which are also a breaking change from POV of everyone already working with us). 

2) suggested simplification makes it somewhat harder to test contracts against different environments. It's a feature that config comes with a set of environments ready to go. I want to be able to test app on different pre-made hosted environments with all setup already provided. I want to be able to also use near-shell in my app context and have it read app-specific config when available.

> and possibly put credentials in this file as well, as suggested here: #339 (review)

credentials should really be moved out of files (for production stuff at least) and into stuff like local storage, signing using Ledger, external mobile device (https://github.com/near/near-wallet/issues/561), etc.
