### ISSUE TITLE
Should we have confirmations for MainNet?

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#413]
Currently on TestNet we can easily send millions of NEAR even by mistake.
 Do we want to add for mainnet network confirmations, like
 ```
 send blah illia 100000000

Transfering 100,000,000 NEAR from blah to illia. Gas spent: 2Tgas. Approximate tx cost: ~1 milliNEAR

Proceed? <span class="error">[Y/n]</span>
 ```

Open for discussion.

**Comment by bowenwang1996** [comment]
Sounds reasonable. We can probably have confirmation if it involves transferring some nontrivial amount of tokens.

**Comment by vgrichina** [comment]
I think `y/n` confirmations are close to being useless in terms of providing safety. Everyone just trains to answer `y` mindlessly. It has to be something that actually requires mental work (like entering receiver / amount again). However there should also be command line option to override (similar to  e.g. `rm -rf`) so that shell can be used for scripting.

Note that for mainnet generally we also would have either multisig confirmation or Ledger confirmation, otherwise we already are in pretty unsafe situation (unencrypted keys on single machine).
