### ISSUE TITLE
Can't schedule non JSON call

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-cli#503]
***Describe the bug***
 Can't schedule a function call that takes arguments not in JSON format, e.g. raw string. 

***To Reproduce***
 ```bash
 near call exchange.m0 exchange_deposit 'USER_123' --accountId=<ACCOUNT_ID>
 ```

***Expected behavior***
 A function call successfully executed without crashing. Or telling me to use argument like `--raw_input`

***Screenshots***
 ```bash
 near call exchange.m0 exchange_deposit 'USER_123' --accountId=m0 --amount=0.1
 ```

```
 Scheduling a call: exchange.m0.exchange_deposit(USER_123) with attached 0.1 NEAR
 Error: SyntaxError: Unexpected token U in JSON at position 0
 at JSON.parse (<anonymous>)
 at scheduleFunctionCall (/Users/ekwork/.config/yarn/global/node_modules/near-shell/commands/call.js:31:14)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async Object.handler (/Users/ekwork/.config/yarn/global/node_modules/near-shell/utils/exit-on-error.js:37:9)
 ```

***Desktop (please complete the following information):***

*   OS: MacOS
*   Version `0.24.9`
*   NEAR_ENV=testnet

***Additional context***
 This is needed to support exchange deposits with a custom memo message.

**Comment by luciotato** [comment]
I vote not to mark this as a bug. Enforcing args to be JSON and to match named contract parameters is a good thing.

**Proposal Number 1**: If the solution is to create a `coin_exchange` contract and make a contract call for the initial deposit, maybe we can just use standard JSON args instead of a string: 

`near call coin_exchange exchange_deposit '{"user":"USER_123"}' --accountId=token_owner --amount=10`

**Proposal Number 2**: Considering that NEAR accountIds are human-readable, not just addresses, why can't the exchange use the depositor's accountId as user name?, then the hot-wallet deposit & account creation becomes a simple transfer:

`near send lucio.testnet hotwallet.coin_exchange.testnet 10`

* The transaction gets executed and the exchange's hot wallet account receives the 10N from accountId=lucio.testnet
* Exchange monitors incoming transactions and sees that this deposit is from `lucio.testnet`
* The exchange can now attribute 10N for to the user: `lucio.testnet`

**Comment by evgenykuzyakov** [comment]
near shell is a tool. It should support everything allowed to be done by the protocol. It's supported by the protocol to use any arguments format and eventually the community might decide to not use JSON at all and use binary format instead. Similar how EVM supports positional arguments 32 bytes each.

I'd also want to be able to pass input in `base64` format to be able to pass binary data in.

> The exchange can now attribute 10N for to the user: `lucio.testnet`

It's true, but the exchange can't match owner `lucio.testnet` with the centralized account logged in with the email. For this they need a `memo` or support more complicated login with NEAR flow. Some mobile wallets might not support more complicated login flows at the beginning.

**Comment by vgrichina** [comment]
@evgenykuzyakov a bit offtopic, but make sure to switch to near-cli package (instead of near-shell) to get most up to date version

**Comment by vgrichina** [comment]
Should we have `--rawArgs` for string passed as is and `--base64Args` for base64-encoded? @evgenykuzyakov

**Comment by luciotato** [comment]
I dived into `near-cli call` code and as far as I can see, the params must be JSON, must be an object, and the JSON gets converted into values for the contract pub fn params.

maybe we can set a prefix to convert certain arguments, for example:

     near call mycontract sotorebindata '{"data-Base64:":"TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx"}' --amount=10

     near call mycontract sotorebindata '{"data-0x":"FA7683B838CA"}' --accountId=token_owner --amount=10

and decode that before calling the actual contract function, which will receive binary data in the fn parameter `data`

What I don't see possible is to do this: 

          near call exchange.m0 exchange_deposit 'USER_123' --accountId=m0 --amount=0.1

without converting it to JSON maybe using a default parameter name, as in:

          near call exchange.m0 exchange_deposit '{"data":"USER_123"}' --accountId=m0 --amount=0.1
