### ISSUE TITLE
Key is present, signer is not able to see it

### ISSUE THREAD

**Issue by gaia** [near/near-cli#515]
near-shell 1.0.3
npm 6.14.6
node 12.18.3
cargo 1.46.0
rustc 1.46.0
ubuntu 18.04

![image](https://user-images.githubusercontent.com/87547/91629020-fc370400-e979-11ea-9a3f-b7e378fe6914.png)

while 

![image](https://user-images.githubusercontent.com/87547/91629027-0d801080-e97a-11ea-82eb-90814f1c63ec.png)

**Comment by mikedotexe** [comment]
thanks for reporting @gaia , can you check to make sure you have the associated key in `~/.near-credentials` somewhere?
Also, typically I prefix this NEAR CLI command with `NEAR_ENV=mainnet near call…`
Otherwise it defaults to using testnet. Could you try that?

**Comment by gaia** [comment]
Keys had been generated (as instructed by the email inviting to create mainnet accounts) as `near generate-key gaia`, not `near generate-key gaia.near`

the key file name was gaia.json with `"account_id":"gaia"`

changing the file name to gaia.near.json fixed the issue, the key now works.

@mikedotexe suggested to also change `"account_id":"gaia"` to `"account_id":"gaia.near"`. this was also done. still works.

maybe prevent `near generate-key` from accepting input without a valid suffix to the account name?

**Comment by bowenwang1996** [comment]
> maybe prevent near generate-key from accepting input without a valid suffix to the account name?

Not sure what you mean. `gaia` is a valid account id.

@mikedotexe should we close this issue now that it is resolved?

**Comment by gaia** [comment]
> Not sure what you mean. `gaia` is a valid account id.

but the filename must be `joe.near.json` even if the account id is just `joe`?
or should the filename and the account id be identical (minus .json)?

**Comment by mikedotexe** [comment]
Thanks for all the feedback.

> as instructed by the email inviting to create mainnet accounts

I'd love to make sure we correct this. Could I get some info on who sent this email? Thanks!

And to what Bowen mentioned, it _is possible_ to have `gaia` as an account name. In a later phase, we'll be auctioning short "top-level accounts" like this. So, for instance I can purchase `mike` instead of `mike.near` at a later point.

**Comment by gaia** [comment]
not sure if it was an email. maybe it was a ann. but i generated keys

```
Account name: gaia.near (funding acct)
Public key: ed25519:DUnYUTBtzHqUvKUim2ZXRHJVtwbjyoU2VqGS1dLu8baf

Account name: fresh.near (just reserving the name)
Public key: ed25519:39mtn6H92UR82avZx8bvyNZ2UuCHL2JnCxMecM9dUMQa 
```

and sent them to Illia, per instructions, who funded the accounts

**Comment by mikedotexe** [comment]
Thanks again for reporting, @gaia 
I'll make sure we make this more clear about the different between top-level accounts and mainnet accounts with the `.near` suffix.
Tried out the `generate-key` command and I believe it's working as expected, except we need better docs and info about it :)

<img width="1003" alt="Screen Shot 2020-08-31 at 11 33 50 AM" src="https://user-images.githubusercontent.com/1042667/91754308-0d506280-eb7e-11ea-9e4a-6d4ce7784824.png">


Thanks again and I believe this issue is good to close now.
