### ISSUE TITLE
create account with ledger does not work properly

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-cli#539]
When I try to create a new account with a given public key, if you pass in `--useLedgerKey`, the new account would be created with the ledger public key instead of the public key I pass in. The command I ran is
 ```
 near create-account <new_account_id> -~~masterAccount=<account_id> --publicKey=<new_public_key>~~-initialBalance=1 --useLedgerKey
 ```
 and the near-cli version I used is 1.0.3.

**Comment by mikedotexe** [comment]
I feel like it's not expected behavior to manually add a public key when using a Ledger. I thought the idea was that you get the public key _from_ Ledger.
Like for me to get my own public key, I ran:
`near generate-key mike.near --useLedgerKey` and it told me the public key.
@vgrichina do you know if Bowen's approach should work?

**Comment by bowenwang1996** [comment]
> I feel like it's not expected behavior to manually add a public key when using a Ledger

Why? What if you want to do a key rotation?

**Comment by mikedotexe** [comment]
@bowenwang1996 I think if you want to do key rotation you'd change the [HD path](https://medium.com/myetherwallet/hd-wallets-and-derivation-paths-explained-865a643c7bf2) and remove the other one.
Get another public key from Ledger like so (the important number being the last 2 at the end:
`near generate-key --useLedgerKey="44'/397'/0'/0'/2'"`
then add it with:
`NEAR_ENV=mainnet near add-key myaccount.near aBCDMgRyLd4808bDf2A2VehTyC808df4oFxvFehGMyKe --useLedgerKey`
(when you don't specify the HD path it uses a default, ending in 1)

**Comment by bowenwang1996** [comment]
I responded wrongly. It was not related to key rotation. If you have an account with only ledger keys, you should be able to create some other account with a different key (not necessarily from the same ledger).

**Comment by branfts** [comment]
Running into this same issue myself.  In my case my goal is to use two ledger keys, one a "hot" key and the other "cold" as in kept away in a safe place.  So, when I perform the same command as @bowenwang1996 

`near add-key <new_account_id> <new_public_key> --useLedgerKey`

I just get
![image](https://user-images.githubusercontent.com/99556664/184946207-0019d603-dfa2-4f2a-be2b-b4dfb059f3b5.png)

The reason for "manually add"ing a public key is due to the fact that having two ledger devices connected at the same time isn't supported (or at least I not that I'm aware of), thus the steps must be:

1. key must be generated using the 1stLedger device, 
2. disconnect 1st device
3. connect 2nddevice
4. add generated key from first device using 2nd device

Anyone have a solution or workaround to this...?
