### ISSUE TITLE
`near login` without "Import existing account"

### ISSUE THREAD

**Issue by frankbraun** [near/near-cli#685]
It seems like `near login` requires me to use "Import existing account", *even* if I'm already logged into an account.

Is this the expected behavior? It would be great if I could just use an account I'm already logged into.

**Comment by mikedotexe** [comment]
hey Frank, so "near login" actually just means "Create a key pair file locally, open up a browser window to NEAR Wallet with the public key as a parameter, and have Wallet's access key agree to add that as a full-access key." So I could say I'm currently "logged in" to all my testnet accounts because I have several keys located in `~/.near-credentials/testnet`
Does that clarify?
This is different than what I believe you're suggesting, which reminds me of using AWS Elastic Container Service where you kind of "log in" to one account. Perhaps that's the mental model you have in your head.

**Comment by frankbraun** [comment]
Thanks for clarifying, it makes more sense now to me. I'm closing the issue.
