### ISSUE TITLE
Improve messages for `generate-key`

### ISSUE THREAD

**Issue by volovyks** [near/near-cli#786]
When we run `near generate key <accId> --seedPhease=<seed>` we are always getting `Account has existing key pair with ed25519:<pk> public key`. It happens even when account Id and pk are not in our local storage.

Another issue:
 When we run simple `near generate-key <acc-name>` we are getting `Key pair with ed25519:<pk> public key for an account "<acc>"` which is not very informative. Let's explain user where this key is stored.

Another issue:
 When the key is already stored - we are getting the same message `Account has existing key pair with XXX`, but the existing key is replaced with the generated one. So.. the user can lose his private key. The user should be prompted that the key will be overwriteen.

**Comment by volovyk-s** [comment]
Related issues:
- https://github.com/near/near-cli/issues/837
- https://github.com/near/near-cli/issues/783
- https://github.com/near/near-cli/issues/326

**Comment by june07** [comment]
Ditto.  This seems like very poor wording...
"Account has existing key pair"

Although yes, the account does JUST NOW after running the generate-key command, have an "existing" key pair... but existing in this context makes it seem like a different key pair existed before the command was run.

Maybe something along the lines of "Key pair has been generated" or some such...

This should be a relatively easy fix... anyone able to provide feedback on different verbiage?

**Comment by lostpebble** [comment]
I'm new to Near development and just encountered this in the CLI. It was very confusing, as the account doesn't even exist on the blockchain yet (just used some random unique name)- and I was generating a key for the first time from a random seed phrase.

It was even more confusing, because just before this I had used a seed phrase with an account that _does_ exist (but wasn't in my local `~/near-credentials` folder yet)- and I got the same message, which I assumed it was telling me that this key pair already existed for this account, as if it did a check on the blockchain. But its still a confusing message to get, because that has nothing to do with the fact that we're adding the key locally now.
