### ISSUE TITLE
Missing `near stake` documentation

### ISSUE THREAD

**Issue by nikurt** [near/near-cli#853]
Neither of the following resources document how to generate a staking transaction using `near-cli`:
* https://docs.near.org/docs/tools/near-cli
* `near --help`
* https://github.com/near/near-cli/blob/master/README.md

The use is intuitive, but a few details surprised me:
* `--amount` specifies whole nears, not yoctos.
* Negative amounts work as un-staking.
* Error message for un-staking too much is confusing. It looks like I'm trying to stake too much.

```
% NEAR_ENV=betanet near stake --amount='-999990000000' --accountId=node1 --stakingKey=<SOME_PUBLIC_KEY> 
Staking -999990000000 (-999990000000000000000000000000000000) on node1 with public key = <SAME_PUBLIC_KEY>.
Receipt: 
        Failure [node1]: Error: Account node1 tried to stake 999,990,000,000, but has staked 350,029,590.690888307430756965091201 and only has 78,290,345.134193986258512965229232
```

**Comment by shitty-dev** [comment]
Is there any possibility to unstake tokens using CLI?
I didn't find any documentation about it



I enabled email and ledger simultaneously, then cleared cookies because there was some issue with website and since then I can't connect via web wallet

I have access via near-cli, so I need to know how to unstake tokens using cli, or somehow restore my access to web wallet

This is old web wallet bag , devs admitted it, we discuss it in telegram group, but they still haven't solved it

This is what happening when I'm trying to enter my wallet using ledger:
[https://monosnap.com/file/HMazLpiXSHYIoQTxYyeLTmrBNB2TTI](url)

Tried to get help in Discord, Telegram, also opened ticket 20 days ago and still haven't got reply

**Comment by volovyk-s** [comment]
@shitty-dev let's move this discussion to our Discord server. But I will try to give you a basic answer here:
This action is not available in `near-cli`, but:
- It should be possible to do it if you still have a private key on your PC.
- To unstake, wallet is making a function call here: https://github.com/near/near-wallet/blob/c5403881cc74bb2e0e97b862b61a905b4e8923b6/packages/frontend/src/redux/actions/staking.js#L109
- It's possible to make the same call from your console with `NEAR CLI` or `curl`.
I would recommend you to ask for help in development channels.
