### ISSUE TITLE
`create-account` does not save the keypair

### ISSUE THREAD

**Issue by telezhnaya** [near/near-cli#865]
I play with localnet.
 I'm running the command
 ```
 NEAR_ENV=local near create-account olya.test.near --initialBalance 5 --masterAccount test.near --keyPath=./validator_key.json
 ```

The answer is 
 ```
 Loaded master account test.near key from ./validator_key.json with public key = ed25519:3ZjUyKAsmRp8RcsrdtfkVmNV4XZP9qfU4XKZtJ6yBn5j
 Saving key to 'undefined/local/olya.test.near.json'
 Account olya.test.near for network "local" was created.
 ```

The account is created, but it's impossible to find their credentials

**Comment by soonnear** [comment]
I think this issue was caused by the assumption on the first element of the array and that each object is implemented as a file system storage (instead of in-memory)
- https://github.com/near/near-cli/blob/47e656177135b27e738c593c6e6960dbdfc7ad2d/commands/create-account.js#L128

Not all implementations of KeyStore has the `keyDir` member variable as it's not part of the interface
- https://github.com/near/near-api-js/blob/master/packages/near-api-js/src/key_stores/keystore.ts
- https://github.com/near/near-api-js/blob/ec8932eb4f8cd5193e4cdea88615994473bad2d8/packages/near-api-js/src/key_stores/unencrypted_file_system_keystore.ts#L83
- https://github.com/near/near-api-js/blob/ec8932eb4f8cd5193e4cdea88615994473bad2d8/packages/near-api-js/src/key_stores/in_memory_key_store.ts#L31-L38
- https://github.com/near/near-api-js/blob/ec8932eb4f8cd5193e4cdea88615994473bad2d8/packages/near-api-js/src/key_stores/merge_key_store.ts#L44-L54

This leads to the 'undefined' string as above.
