### ISSUE TITLE
Cannot connect to local node from host but can from external

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-cli#881]
reopening https://github.com/near/near-cli/issues/873

OS:
Debian 11

Can you explain this. Why is `http://localhost:3030/status` success and `NEAR_ENV=local near state local.test` fail

https://user-images.githubusercontent.com/4870868/142728275-88c6cc8f-24f9-4770-a669-f1da16a0c3b1.mp4

**Comment by evergreen-trading-systems** [comment]
But I can connect from external machine

https://user-images.githubusercontent.com/4870868/142728462-0ab148d0-f677-413e-8c89-80479d38932c.mp4


Please fix this bug

**Comment by evergreen-trading-systems** [comment]
To reproduce

Please install Debian 11 Bullseye from fresh. Make sure `lsb_release -a` shows
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Install Nodejs v17 and near API cli

Install Rust 1.56 and run local indexer from https://github.com/near/near-indexer-for-explorer

If it work show video

**Comment by evergreen-trading-systems** [comment]
specifying `--nodeUrl http://127.0.0.1:3030` works but not great

https://user-images.githubusercontent.com/4870868/142728920-9474a207-8156-4685-8714-0a5060a5aa26.mp4

**Comment by volovyk-s** [comment]
@evergreen-trading-systems `local.test` is not a valid acc name. For standard local setup please use `test.near`.

**Comment by evergreen-trading-systems** [comment]
That was a typo but it doesn't change anything because if it was working, it would say `local.near does not exist` instead `ECONREFUSED`. On local node I believe root account name is configurable.

**Comment by volovyk-s** [comment]
@nikurt since you are working a lot with local nodes, maybe you can suggest something here?

**Comment by nikurt** [comment]
Is the video in the description is taken on a Windows machine?
Crazy idea. Can it be that `localhost` is resolved to an ipv6 address but the node is only listening on ipv4 addresses?

**Comment by evergreen-trading-systems** [comment]
Yes there are 2 machines, windows and debian. I can connect from windows to debian. Also from debian but using `http://127.0.0.1:3030` not `http://localhost:3030`. Don't know how I can connect to ipv6 address.

**Comment by nikurt** [comment]
Actually, my crazy idea seems to be correct.
In the original video, at 0:47, you can see that a connection refused comes from `::1:3030` which is indeed the ipv6 `localhost`.
Different systems resolve `localhost` using different methods.
Two possible solutions:
1. near-cli should connect to 127.0.0.1 rather than localhost
2. nodes should also listen on ipv6 addresses, such as `::` in addition to `0.0.0.0`.

**Comment by volovyk-s** [comment]
@evergreen-trading-systems 
Please, try to override all config values that have `localhost` to IPv4 addresses. It's possible by changing this `env` variables: https://github.com/near/near-cli/blob/69319062495bc23fceb9a2276f7e6f209fa28887/config.js#L48

**Comment by marcelo-gonzalez** [comment]
@evergreen-trading-systems I was able to reproduce your issue actually..

@volovyk-s I'm not sure exactly what's going on, but I think it has something to do with the use of `node-fetch` in `near-api-js`. I'm reproducing this by running `docker run --rm -it --entrypoint /bin/bash --network host debian:bullseye` and (after running apt install for a few things) running the command `NEAR_ENV=local near state test.near`. I get the same conn refused error, so I tried with the following saved to `./fetch.mjs` from inside a `near-api-js` repo:

```javascript
import fetch from 'node-fetch';
import http from 'http';
import https from 'https';

const httpAgent = new http.Agent({ keepAlive: true });
const httpsAgent = new https.Agent({ keepAlive: true });

function agent(_parsedURL) {
    if (_parsedURL.protocol === 'http:') {
        return httpAgent;
    } else {
        return httpsAgent;
    }
}

function fetch2(resource, init) {
    return fetch(resource, {
        agent: agent(new URL(resource.toString())),
        ...init,
    });
}

let json = null;

console.log(await fetch2("http://localhost:3030", {
    method: json ? 'POST' : 'GET',
    body: json ? json : undefined,
    headers: { 'Content-Type': 'application/json; charset=utf-8' }
}));

```

This is basically what is in https://github.com/near/near-api-js/blob/master/src/utils/setup-node-fetch.ts, so there seems to be some problem with that.

**Comment by marcelo-gonzalez** [comment]
@volovyk-s  I took another look at this, and I'm quite sure it's the same as this issue: https://github.com/nodejs/node/issues/40702

The reproducer given in that issue seems to work on Debian 10 but fails on Debian 11, also the snippet in [this comment](https://github.com/nodejs/node/issues/40702#issuecomment-958143154) gives an IPv4 addr on Debian 10 but an IPv6 one on Debian 11: `require('dns').lookup('localhost', null, (e,a,f) => console.log(e,a,f))`

In that case I think changing near-cli to use `127.0.0.1` instead of `localhost` would probably be the way to go.

**Comment by volovyk-s** [comment]
Thanks @marcelo-gonzalez ! Let's ask @evergreen-trading-systems to double-check if it will work. I'm afraid that `localhost` -> `127.0.0.1` can create more problems.
@evergreen-trading-systems please, try to use env variables to override RPC Url and tell us if it worked for you.
https://github.com/near/near-cli/blob/master/config.js#L48

**Comment by treysis** [comment]
> I'm afraid that `localhost` -> `127.0.0.1` can create more problems.

Could you elaborate why? Because actually changing `localhost` to `127.0.0.1` should be the way to go. Alternatively you can downgrade NodeJS to v16 which is LTS version.

The reason why it's working with `curl` is that curl supports "Happy Eyeballs", i.e. it tries to connect to the IPv6 address, will failover and use the IPv4 address instead. Unfortunately, NodeJS doesn't support Happy Eyeballs. Either it succeeds on first try or it fails.

**Comment by nikurt** [comment]
Given that all IP addresses in the protocol are IPv4-only, such as node's rpc_addr and network peer addresses - it totally makes sense to me to have IPv4-only addresses in near-cli
