### ISSUE TITLE
Add ability to view-state in deserialized format and not borsh

### ISSUE THREAD

**Issue by chefsale** [near/near-cli#887]

**Comment by frol** [comment]
Borsh is not a self-descriptive format, so you cannot just bring some data blob and deserialize it. Thus, you would need to bring the schema with you. If you have it in Rust, e.g.:

```rust
#[derive(BorshSerialize)]
struct MyStruct {
    name: String
}
```

then you can copy-paste it and write a simple Rust program:

```rust
use borsh::{BorshSerialize, BorshDeserialize};

#[derive(BorshSerialize, BorshDeserialize, Debug)] // <----
struct MyStruct {
    name: String
}

fn main() {
    let binary_blob = vec![/* bytes */];
    let my_struct_value = MyStruct::try_from_slice(&binary_blob).expect("unable to deserialize MyStruct");
    println!("{:#?}", my_struct_value);
}
```

**Comment by chefsale** [comment]
OK, makes sense. The problem for me as a user I'm calling view-state and expect to see something human readable, I have no idea of what the actual state of the contract I'm trying to look the state for is. 

Is there a way to implement that logic into the near cli tool without me ever need to think about the state schema?

**Comment by volovyk-s** [comment]
@chefsale unfortunately it's not possible. In `Borsh` you are always encoding data with a schema. The structure of the data is not saved in the encoded result (so it becomes smaller!). At the same time, it is not possible to decode this data without the schema that was used during encoding.

**Comment by frol** [comment]
There is no way to do that at the moment since near-cli / RPC / nearcore / NEAR protocol only know that the keys and values are binary data. We could try to deserialize those as strings / JSON values, but not borsh. In the general case, contracts actually call `storage_write(binary_key, binary_value)`, and it is near-sdk-rs which provides the magic of serializing Rust structs into those binary values and given that borsh does not have a schema, there is no way to read it without the source code or some explicit dump of the schema, and in the general case, we don't have access to the source code (unless it is open-sourced and easily discoverable, and even in that case, we cannot automatically extract borsh schema out of it).
